config/routes.rb
Rails.application.routes.draw do
  
  resources :tweets , only:[:index,:new,:create,:destroy,:edit,:update]do
    collection do
      post :confirm
    end
  end
  root 'top#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :content,presence: true, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :destroy]
  def index
    @tweets=Tweet.all
  end
  def create
    @tweet = Tweet.new(tweets_params)
    if @tweet.save
      redirect_to tweets_path,notice:'Tweetしました'
    else
     render 'new'
    end
  end
  def confirm
     @tweet = Tweet.new(tweets_params)
     render :new if @tweet.invalid?
  end
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path,notice:"Tweetを削除しました"
  end
  def new
     if params[:back]
        @tweet = Tweet.new(tweets_params)
      else
        @tweet = Tweet.new
      end
  end
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweets_params)
      redirect_to tweets_path
    else
      render'edit'
    end
  end
  private
   def tweets_params
    params.require(:tweet).permit(:content)
   end
   def set_tweet
      @tweet = Tweet.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def choose_new_or_edit
     if action_name == 'new' || action_name == 'confirm'
       confirm_tweets_path
     elsif action_name == 'edit'
       edit_tweet_path
     end
 end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>

app/views/tweets/_form.html.erb
<div class="container">
   <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.label :content,"内容"%>
<%= f.text_field :content, class: 'form-control'  %>
<br>
<%= f.submit"tweet", class: 'btn btn-primary btn-block' %>
<% end %>
<%= link_to '戻る', :back, class: 'btn btn-default btn-block' %>

</div>
</div>

app/views/tweets/confirm.html.erb
<div class="container">
   <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h3>以下の内容で、送信する。</h3>

<%= form_for(@tweet) do |f| %>
  <%= f.hidden_field :content %>
  <p>本文:<%= @tweet.content %></p>
  <%= f.submit "tweet" ,class: 'btn btn-primary btn-block'%>
<% end %>
<%= form_for(@tweet, url: new_tweet_path, method: 'get') do |f| %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", class: 'btn btn-default btn-block' %>
<% end %>
</div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
   <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h2>Tweetを編集する</h2>
<%= form_for(@tweet) do |f| %>
<%= f.label :content ,"内容"%>
<%= f.text_field :content, class: 'form-control'  %>
<br>
<%= f.submit"tweet", class: 'btn btn-primary btn-block' %>
<%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block'  %>
<% end %>
</div>
</div>

app/views/tweets/index.html.erb
<header>
  <ul>
    <li><a href="#">ホーム</a></li>
    <li><a href="#">モーメント</a></li>
    <li><a href="#">通知</a></li>
    <li><a href="#">メッセージ</a></li>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Tweet", new_tweet_path, class: 'btn btn-primary' %></li>
  </ul>
    </ul>
    </div>
</header>
<div class="container">
   <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<%= notice %>
<h1>Tweets</h1>

<% @tweets.each do |tweet| %>
<div class="row">
  <p>本文:<%= tweet.content %></p>
  <%= link_to "編集", edit_tweet_path(tweet.id), class: 'btn btn-default btn-sm btn-success'  %>
  <%= link_to '削除', tweet_path(tweet.id), method: :delete,data: { confirm: '本当削除していいですか？' }, class: 'btn btn-default btn-sm btn btn-danger'  %>
</div>
<% end %>
  </div>
</div>

app/views/tweets/new.html.erb
       <h2>Tweetする</h2>
<%= render 'form' %>